[build]
base = "/"
publish = "build/web"
command = "bash ./netlify_build.sh"

[build.environment]
# Ensure Flutter is available
FLUTTER_VERSION = "3.24.0" # change to your Flutter version
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,SUPABASE_ANON_KEY"


