name: admin_dashboard_rajshree
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core utilities
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  logger: ^2.0.0
  intl: ^0.20.2
  http: ^1.2.2

  # File & Storage
  file_picker: ^8.0.0
  path_provider: ^2.1.4
  file_saver: ^0.3.1

  # Supabase
  supabase_flutter: ^2.9.1

  # Documents / PDF
  pdf: ^3.10.4
  printing: ^5.12.0
  excel: ^4.0.6
  csv: ^5.0.2
  barcode: ^2.2.4

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.13

  # Google APIs (if needed)
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/fonts/Roboto-Regular.ttf
